export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_SUCCESSFULLY = 'FETCH_STUDENTS_SUCCESSFULLY';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const DELETE_STUDENTS = 'DELETE_STUDENTS';

export const CREATE_STUDENT = "CREATE_STUDENT";
export const CREATE_STUDENT_SUCCESSFULLY = "CREATE_STUDENT_SUCCESSFULLY";
export const CREATE_STUDENT_FAILURE= "CREATE_STUDENT_FAILURE";

